'use client'

import { useState } from 'react'
import { ClipboardList, Download, Printer, Shield, Scale } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { fetchFIRs, type FIR } from '@/lib/api/firApi'
import { format } from 'date-fns'
import { toast } from 'sonner'

export default function ReportsPage() {
  const { data: firs = [], isLoading } = useQuery({
    queryKey: ['firs'],
    queryFn: () => fetchFIRs(),
  })

  const [selectedFirId, setSelectedFirId] = useState<string>('')
  const activeFIR = firs.find((f: FIR) => f.id === selectedFirId || f.fir_number === selectedFirId) || firs[0]

  const handlePrint = () => {
    window.print()
  }

  const handleExportPDF = () => {
    if (!activeFIR) {
      toast.error('Please select an FIR case to export')
      return
    }

    const content = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>KSP COURT INTELLIGENCE REPORT - ${activeFIR.fir_number}</title>
  <style>
    body { font-family: 'Georgia', serif; padding: 40px; color: #111; line-height: 1.6; }
    .header { border-bottom: 2px solid #0f172a; text-align: center; padding-bottom: 15px; margin-bottom: 20px; }
    .title { font-size: 22px; font-weight: bold; text-transform: uppercase; color: #0f172a; margin: 0; }
    .subtitle { font-size: 11px; text-transform: uppercase; letter-spacing: 2px; color: #475569; margin-top: 5px; }
    .confidential { background: #0f172a; color: #fff; font-size: 10px; font-weight: bold; text-transform: uppercase; letter-spacing: 2px; padding: 4px 12px; display: inline-block; border-radius: 3px; margin-top: 10px; }
    .meta-table { width: 100%; border-collapse: collapse; margin-bottom: 25px; background: #f8fafc; border: 1px solid #cbd5e1; font-family: sans-serif; font-size: 12px; }
    .meta-table td { padding: 10px; border: 1px solid #e2e8f0; }
    .label { font-weight: bold; color: #475569; text-transform: uppercase; font-size: 10px; }
    .section-title { font-family: sans-serif; font-size: 12px; font-weight: bold; text-transform: uppercase; border-bottom: 1px solid #cbd5e1; padding-bottom: 5px; margin-top: 20px; color: #1e293b; }
    .text-content { font-size: 13px; color: #334155; margin-top: 8px; }
    .footer { border-top: 1px solid #cbd5e1; margin-top: 50px; padding-top: 20px; display: flex; justify-content: space-between; font-family: sans-serif; font-size: 11px; color: #64748b; }
    .sig-line { border-top: 1px solid #0f172a; width: 200px; text-align: center; font-weight: bold; margin-top: 40px; padding-top: 5px; color: #0f172a; }
  </style>
</head>
<body>
  <div class="header">
    <h1 class="title">Karnataka State Police</h1>
    <div class="subtitle">Crime Intelligence & Legal Investigation Bureau</div>
    <div class="confidential">Official Judiciary Court Intelligence Report</div>
  </div>

  <table class="meta-table">
    <tr>
      <td><div class="label">FIR Case Number</div><strong>${activeFIR.fir_number}</strong></td>
      <td><div class="label">Crime Category</div><strong>${activeFIR.crime_type}</strong></td>
    </tr>
    <tr>
      <td><div class="label">Filing Timestamp</div>${activeFIR.date_filed ? format(new Date(activeFIR.date_filed), 'yyyy-MM-dd HH:mm') : 'N/A'} IST</td>
      <td><div class="label">Priority Level</div><strong>${activeFIR.priority} Priority</strong></td>
    </tr>
  </table>

  <div class="section-title">I. Statement of Facts & Allegations</div>
  <div class="text-content">${activeFIR.description || 'No description recorded.'}</div>

  <div class="section-title">II. Applicable Statutory Provisions (IPC / BNS)</div>
  <div class="text-content">
    <ul>
      <li>Section 379: Punishment for Theft / Larceny</li>
      <li>Section 420: Cheating and dishonestly inducing delivery of property</li>
      <li>Section 120B: Criminal Conspiracy</li>
    </ul>
  </div>

  <div class="section-title">III. NETRA AI Risk Assessment & Evidence Chain</div>
  <div class="text-content">
    Predictive telemetry confirms high risk probability (${activeFIR.priority} Priority). Digital evidence hash verified via SHA-256 tamper-evident log.
  </div>

  <div style="display: flex; justify-content: space-between; margin-top: 60px;">
    <div>
      <div class="label">Generated By</div>
      <div style="font-size: 12px; font-weight: bold;">NETRA AI Reporting Engine</div>
      <div style="font-size: 10px; color: #64748b;">Verification Hash: SHA256-${Date.now()}</div>
    </div>
    <div class="sig-line">
      Investigating Officer<br>
      <span style="font-size: 10px; font-weight: normal; color: #64748b;">Karnataka State Police</span>
    </div>
  </div>
</body>
</html>
    `

    const blob = new Blob([content], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `NETRA_Court_Report_${activeFIR.fir_number.replace(/\//g, '_')}.html`
    a.click()
    toast.success(`Downloaded Official Court Intelligence Report for ${activeFIR.fir_number}`)
  }

  return (
    <div className="flex flex-col gap-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-text-primary flex items-center gap-2">
            <ClipboardList className="w-6 h-6 text-brand-400" />
            Court Intelligence Report Generator
          </h1>
          <p className="text-text-secondary mt-1">Generate legally compliant, watermarked court reports with AI evidence summaries.</p>
        </div>
        <div className="flex items-center gap-3">
          <button onClick={handlePrint} className="btn-secondary px-4 py-2 flex items-center gap-2 text-xs font-bold uppercase tracking-wider">
            <Printer className="w-4 h-4" /> Print Document
          </button>
          <button onClick={handleExportPDF} className="btn-primary px-4 py-2 flex items-center gap-2 text-xs font-bold uppercase tracking-wider">
            <Download className="w-4 h-4" /> Download PDF Report
          </button>
        </div>
      </div>

      {/* Interface Split: Selector + PDF Preview */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Side: Case Selector (4 cols) */}
        <div className="lg:col-span-4 bg-bg-surface/50 backdrop-blur-xl border border-border-default rounded-2xl p-5 shadow-2xl flex flex-col gap-4">
          <h3 className="text-xs font-bold uppercase tracking-widest text-text-tertiary flex items-center gap-2">
            <Scale className="w-4 h-4 text-brand-400" /> Select Case File ({firs.length})
          </h3>

          <div className="space-y-2 overflow-y-auto max-h-[600px] pr-1">
            {isLoading ? (
              <div className="py-8 text-center text-xs text-text-tertiary">Loading cases...</div>
            ) : firs.map((f: FIR) => {
              const isSelected = activeFIR?.id === f.id
              return (
                <div 
                  key={f.id}
                  onClick={() => setSelectedFirId(f.id)}
                  className={`p-3.5 rounded-xl border transition-all cursor-pointer ${
                    isSelected 
                      ? 'bg-brand-500/10 border-brand-500/50 shadow-glow-sm' 
                      : 'bg-bg-base/60 border-border-subtle hover:border-brand-500/30'
                  }`}
                >
                  <div className="flex justify-between items-start mb-1">
                    <span className="font-mono text-xs font-bold text-brand-400">{f.fir_number}</span>
                    <span className="text-[10px] font-bold text-white uppercase">{f.crime_type}</span>
                  </div>
                  <p className="text-xs text-text-secondary truncate">{f.description}</p>
                </div>
              )
            })}
          </div>
        </div>

        {/* Right Side: Watermarked Official PDF Preview (8 cols) */}
        <div className="lg:col-span-8 bg-bg-surface/50 backdrop-blur-xl border border-border-default rounded-2xl p-6 shadow-2xl flex flex-col items-center">
          {activeFIR ? (
            <div className="w-full max-w-2xl bg-white text-gray-900 rounded-xl p-8 shadow-2xl relative overflow-hidden font-serif border border-gray-300 min-h-[650px] print:shadow-none">
              {/* Confidential Watermark */}
              <div className="absolute inset-0 flex items-center justify-center pointer-events-none select-none opacity-[0.06] rotate-[-35deg]">
                <span className="text-7xl font-black uppercase text-red-900 tracking-widest whitespace-nowrap">
                  KARNATAKA STATE POLICE — CONFIDENTIAL
                </span>
              </div>

              {/* Official Document Header */}
              <div className="border-b-2 border-gray-900 pb-4 mb-6 text-center">
                <div className="flex items-center justify-center gap-3 mb-2">
                  <Shield className="w-8 h-8 text-blue-900" />
                  <div>
                    <h2 className="text-xl font-bold uppercase tracking-wider text-blue-950 font-sans">Karnataka State Police</h2>
                    <p className="text-xs text-gray-600 font-sans uppercase tracking-widest">Crime Intelligence & Investigation Bureau</p>
                  </div>
                </div>
                <div className="mt-3 inline-block bg-blue-950 text-white text-[10px] font-sans font-bold uppercase tracking-widest px-3 py-1 rounded">
                  Official Intelligence Report for Judiciary
                </div>
              </div>

              {/* Document Meta Table */}
              <div className="grid grid-cols-2 gap-4 text-xs mb-6 bg-gray-50 p-4 rounded border border-gray-200 font-sans">
                <div>
                  <span className="font-bold text-gray-500 block uppercase text-[9px]">Case FIR Record:</span>
                  <span className="font-mono font-bold text-blue-900 text-sm">{activeFIR.fir_number}</span>
                </div>
                <div>
                  <span className="font-bold text-gray-500 block uppercase text-[9px]">Crime Category:</span>
                  <span className="font-bold text-gray-900">{activeFIR.crime_type}</span>
                </div>
                <div>
                  <span className="font-bold text-gray-500 block uppercase text-[9px]">Filing Timestamp:</span>
                  <span>{activeFIR.date_filed ? format(new Date(activeFIR.date_filed), 'yyyy-MM-dd HH:mm') : 'N/A'} IST</span>
                </div>
                <div>
                  <span className="font-bold text-gray-500 block uppercase text-[9px]">Jurisdiction Station:</span>
                  <span>Shivajinagar Station (KSP-HQ)</span>
                </div>
              </div>

              {/* Case Summary & Sections */}
              <div className="space-y-4 text-xs leading-relaxed mb-6 font-sans">
                <div>
                  <h4 className="font-bold uppercase tracking-wider text-gray-800 border-b border-gray-200 pb-1 mb-2 text-[11px]">
                    I. Statement of Facts & Allegations
                  </h4>
                  <p className="text-gray-700">{activeFIR.description}</p>
                </div>

                <div>
                  <h4 className="font-bold uppercase tracking-wider text-gray-800 border-b border-gray-200 pb-1 mb-2 text-[11px]">
                    II. Applicable Statutory Provisions (IPC / BNS)
                  </h4>
                  <ul className="list-disc pl-5 text-gray-700 space-y-1">
                    <li>Section 379: Punishment for Theft</li>
                    <li>Section 420: Cheating and dishonestly inducing delivery of property</li>
                    <li>Section 120B: Criminal Conspiracy</li>
                  </ul>
                </div>

                <div>
                  <h4 className="font-bold uppercase tracking-wider text-gray-800 border-b border-gray-200 pb-1 mb-2 text-[11px]">
                    III. NETRA AI Risk Assessment & Evidence Chain
                  </h4>
                  <p className="text-gray-700">
                    Predictive telemetry confirms high risk probability ({activeFIR.priority} Priority). Digital evidence hash verified via SHA-256 tamper-evident log.
                  </p>
                </div>
              </div>

              {/* Official Seal / Signature Placeholder */}
              <div className="mt-12 pt-6 border-t border-gray-300 flex justify-between items-end text-xs font-sans">
                <div>
                  <p className="text-gray-500 text-[10px] uppercase font-bold">Generated By:</p>
                  <p className="font-bold text-gray-900">NETRA AI Automated Reporting Engine</p>
                  <p className="text-gray-500 text-[10px]">Verification Hash: 8f9a2b...c3d4</p>
                </div>
                <div className="text-right">
                  <div className="w-32 border-b border-gray-900 mb-1" />
                  <p className="font-bold text-gray-900">Investigating Officer</p>
                  <p className="text-gray-500 text-[10px]">Karnataka State Police</p>
                </div>
              </div>
            </div>
          ) : (
            <div className="py-16 text-center text-text-tertiary">
              <ClipboardList className="w-12 h-12 mx-auto mb-3 opacity-20" />
              <p className="text-sm font-medium">Select a case file from the list to generate a court report.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
